# Configuration file for list of people and corresponding email addresses.
# Lists after the colon (':') should be separated by commas (',') and should 
# contain no spaces. The secondary keys should be email (required) and exclude
# (optional). The number of people in the exclude list should be kept to a minimum.

Person1:
  email: Person1@mail.com
  exclude: Person2
Person2:
  email: Person2@mail.com
Person3:
  email: Person3@mail.com
Person4:
  email: Person4@mail.com