# Configuration file for list of people and corresponding email addresses.
# Lists after the colon (':') should be separated by commas (',') and should 
# contain no spaces. The secondary keys should be email (required) and exclude
# (optional). The number of people in the exclude list should be kept to a minimum.

Person1:
  phone: 213 456 7890
Person2:
  phone: 213 456 7894